import { Metadata } from "next";
import { ErrorWrapper } from "./error-wrapper";

export const metadata: Metadata = {
  title: {
    default: "Routing Demo",
    template: "%s | Routing",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <p style={{ backgroundColor: "lightblue", padding: "1rem" }}>
            Header
          </p>
        </header>
        <ErrorWrapper>{children}</ErrorWrapper>
        <footer>
          <p style={{ backgroundColor: "ghostwhite", padding: "1rem" }}>
            Footer
          </p>
        </footer>
      </body>
    </html>
  );
}
